# SwiftLint Configuration for Gridcrack
# Strict but sensible rules matching project conventions

# Paths to include
included:
  - Gridcrack

# Paths to exclude
excluded:
  - build
  - DerivedData
  - .build
  - Pods
  - Carthage

# ─── Rule Configuration ────────────────────────────────────────────────

# Line length: 120 warning, 200 error (generous for SwiftUI modifiers)
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true

# File length
file_length:
  warning: 400
  error: 600

# Type body length
type_body_length:
  warning: 300
  error: 500

# Function body length
function_body_length:
  warning: 50
  error: 100

# Function parameter count
function_parameter_count:
  warning: 6
  error: 8

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Nesting
nesting:
  type_level: 2
  function_level: 3

# Type name lengths
type_name:
  min_length: 3
  max_length: 50
  allowed_symbols: []

# Identifier name lengths
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - i
    - j
    - r
    - g
    - b

# Large tuples
large_tuple:
  warning: 3
  error: 4

# ─── Enabled Opt-in Rules ──────────────────────────────────────────────

opt_in_rules:
  # Style
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_none_name
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - shorthand_optional_binding
  - sorted_first_last
  - toggle_bool
  - trailing_comma
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - yoda_condition

# ─── Disabled Rules ────────────────────────────────────────────────────

disabled_rules: []

# ─── Trailing Comma ────────────────────────────────────────────────────

trailing_comma:
  mandatory_comma: false

# ─── Modifier Order ────────────────────────────────────────────────────
# Uses default order — no custom override needed

# ─── Multiline Arguments ──────────────────────────────────────────────

multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true

# ─── Reporter ──────────────────────────────────────────────────────────

reporter: "xcode"
