name: Gridcrack
options:
  bundleIdPrefix: com.artshin
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"

targets:
  Gridcrack:
    type: application
    platform: iOS
    sources:
      - Gridcrack
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.artshin.gridcrack
      INFOPLIST_FILE: Gridcrack/Info.plist
      DEVELOPMENT_TEAM: SC5KNP7Z9L
      GENERATE_INFOPLIST_FILE: NO
      SWIFT_VERSION: "5.9"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
